### ISSUE TITLE
🐞 Vertices#Scaling() の動作が不正

### ISSUE THREAD

**Issue by taishi-matsumura** [human-osaka-game-2018/GameFramework#105]
## 不具合概要
Vertices#Scaling() の初回呼び出し時の動作が不正

## 発生バージョン
e2052c2

## 再現手順
1. 引数に5、0.5f、2.0fを設定し `Vertices::ScalingX()` を呼び出す
2. 初回呼び出し時に2倍に拡大される

## 本来の挙動
初回は0.5倍に拡大されること

## 原因

algorithm::SwitchMinBetweenMax() の不具合と思われます

## 補足
_Originally posted by @taishi-matsumura in https://github.com/human-osaka-game-2018/GameFramework/pull/99_

仕様誤認であれば、どういう仕様かを書いた上でinvalidのラベルを貼ってcloseして下さい。

**Comment by Harutaka-Tsujino** [comment]
0～1を行き来する値を作成していると思っていましたが1～0のようになっていました
