### ISSUE TITLE
🚨 カラー構造体のoperator*で暗黙の型変換の警告が出てしまう

### ISSUE THREAD

**Issue by Harutaka-Tsujino** [human-osaka-game-2018/GameFramework#80]
引数でfloat渡されているがそれをintにキャストせず変換しているため警告が出てしまっている

**Comment by taishi-matsumura** [comment]
@Harutaka-Tsujino 
float から int への変換のやつ？
直そうか？

**Comment by Harutaka-Tsujino** [comment]
@taishi-matsumura 
お願いします。

**Comment by taishi-matsumura** [comment]
Pull Request #81 でマージ済み
(プルリクの方のClosesの後の番号間違えてました。すみません)
