### ISSUE TITLE
ライブラリの修正

### ISSUE THREAD

**Issue by Harutaka-Tsujino** [human-osaka-game-2018/GameFramework#94]
- [x] 開放関数をインスタンスが存在していない時は呼ばないようにする
- [x] 追加でプレゼントパラムの値を設定するようにする
- [x] CustomVertexの処理のタイミング修正
- [x] HWNDの更新処理の追加
- [x] バックバッファフォーマットの変更

**Comment by taishi-matsumura** [comment]
@Harutaka-Tsujino 
これ自体がプルリクになってしまってるねー
Issueとプルリクの書き分けに早く慣れて下さいね。

**Comment by Harutaka-Tsujino** [comment]
> @Harutaka-Tsujino
> これ自体がプルリクになってしまってるねー
> Issueとプルリクの書き分けに早く慣れて下さいね。

書き分け頑張ります
